### PR TITLE
Enable branch protection for OpenMQ releases

### PR DESCRIPTION
**Pull request by pzygielo**

### CODE REVIEW

**Comment by netomi** [comment]
LGTM, in case you are not aware, you can merge the change yourself by adding `/otterdog merge`  as comment.

**Comment by pzygielo** [comment]
> in case you are not aware, you can merge the change yourself by adding `/otterdog merge` as comment

I was not aware of having that permission.
Thanks.

**Comment by netomi** [comment]
see https://github.com/eclipse-ee4j/.eclipsefdn/pull/8#issuecomment-2275305712

**Pull request merged**
